version: '3.8'

services:
  postgres:
    image: postgres # You can use the latest stable version here
    container_name: postgres-container
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    ports:
      - "5432:5432" # Exposing port for local access
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist data between container restarts
    networks:
      - postgres-net

volumes:
  postgres-data:
    driver: local

networks:
  postgres-net:
    driver: bridge
